# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=38)),
                ('last_name', models.CharField(default='', max_length=38)),
                ('email', models.CharField(default='', max_length=38)),
                ('password', models.CharField(default='', max_length=38)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
