# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecret', '0004_auto_20170623_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_id',
        ),
    ]
