# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecret', '0006_auto_20170623_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='dojosecret.Book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='dojosecret.User'),
        ),
    ]
